name: "ğŸš€ Publish"

on:
    push:
        branches:
          - master

jobs:
  release:
    name: "ğŸš€ Publish"
    runs-on: macos-13
    environment: npm-publish   # â† nombre del environment
    steps:
      - name: ğŸ“š Checkout
        uses: actions/checkout@v4
      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: ğŸš€ Build & Publish
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn publish --access public --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
